name: .NET Core CI

on:
  push:
    branches: [ "task*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Test
      run: dotnet test